#!/bin/bash

BIN="JSLTests/objc"

function run() {
    if [ "$1" = "0" ]; then
        OUT="step0_repl"
    elif [ "$1" = "1" ]; then
        OUT=step1_read_print
    elif [ "$1" = "2" ]; then
        OUT="step2_eval"
    elif [ "$1" = "3" ]; then
        OUT="step3_env"
    elif [ "$1" = "4" ]; then
        OUT="step4_if_fn_do"
    elif [ "$1" = "5" ]; then
        OUT="step5_tco"
    elif [ "$1" = "6" ]; then
        OUT="step6_file"
    elif [ "$1" = "7" ]; then
        OUT="step7_quote"
    elif [ "$1" = "8" ]; then
        OUT="step8_macros"
    elif [ "$1" = "9" ]; then
        OUT="step9_try"
    elif [ "$1" = "A" ]; then
        OUT="stepA_mal"
    else
        OUT="jsl"
    fi
    $BIN/$OUT "${@:2}"
}

function help() {
    echo "Run requires step as argument"
    echo "Usage: $0 step"
    exit
}

run $@
